spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo_app?useSSl=false
    username: root
    password: admin1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    # <Automatically generate schemes>
    generate-ddl: true
    show-sql: true
    hibernate:
      # <Deprecated>
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create-drop
        
springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: "health, beans, metrics"
        
      base-path: "/management-info"
  endpoint: 
    health:
      show-details: always

# logging:
#   level:
#     org.springframework: DEBUG